### ISSUE TITLE
Split the list in 3 parts?

### ISSUE THREAD

**Issue by HellboyPI** [xRuffKez/NRD#1]
Hello! Thank You for this NRD list! 
Is it possible to split the 30 days list in 3 parts (for easier handling)? That each part does not surpass 40-50 MB in size?

**Comment by xRuffKez** [comment]
What's the issue with file size over 50mb?

**Comment by hagezi** [comment]
I have tested it with 3 parts, same error when updating all lists. The total duration of the update is simply too long, it causes some kind of timeout. 

![grafik](https://github.com/xRuffKez/NRD/assets/104343908/f4c4954d-7e97-4fc5-964e-57b24e1792f4)

**Comment by hagezi** [comment]
@HellboyPI https://github.com/AdguardTeam/AdGuardHome/issues/7041

**Comment by hagezi** [comment]
@HellboyPI will be fixed in next AGH release [v0.107.51](https://github.com/AdguardTeam/AdGuardHome/milestone/52)

See, also: https://github.com/AdguardTeam/AdGuardHome/issues/7041#issuecomment-2148093004

**Comment by xRuffKez** [comment]
Not a bug in AGH but timeout is too low for big lists.

Should be fixed on edge and soon on the next stable release of AGH :)
