### ISSUE TITLE
Error adding list to adguard home Ubuntu 24.04

### ISSUE THREAD

**Issue by GWD72** [xRuffKez/NRD#10]
Love your work and so I hope there is a simple solution to this error.  

Adding this list (https://github.com/xRuffKez/NRD/blob/main/lists/30-day/adblock/nrd-30day_adblock_part1.txt) in the normal way to adguard home in Ubuntu 24.04 resulted in this error: **Error: control/filtering/add_url | Couldn't fetch "https://github.com/xRuffKez/NRD/blob/main/lists/30-day/adblock/nrd-30day_adblock_part1.txt": data is HTML, not plain text | 400**  (I copied the list link directly: https://github.com/xRuffKez/NRD/tree/main/lists/30-day/adblock and was trying to add it to adguard home interface opened in Chrome browser).

Could be you supply the link somewhere else, that will work in my setup, but I couldn't find it.  So if that is the case, perhaps you could make it more visible?

Incidentally, your other list (https://raw.githubusercontent.com/xRuffKez/Phishfort-Domain-Lists/main/phishfort_full_adguardhome.txt) is added with no problems, in the same Chrome browser.

**Comment by hagezi** [comment]
You are using the wrong link, you need to add the RAW link. What you added is the link of the Github page, HTML, that can't work ;)

**Comment by GWD72** [comment]
Wow, that's service. Thanks so much! But where are those links found? I can't find them any longer on your site, nor in the git

**Comment by xRuffKez** [comment]
> Wow, that's service. Thanks so much! But where are those links found? I can't find them any longer on your site, nor in the git

Go to the desired list and click on RAW.
