### ISSUE TITLE
Prisjakt.nu

### ISSUE THREAD

**Issue by miansopi** [xRuffKez/NRD#11]
Somehow ”prisjakt.nu” was included in the NRD 14-day list. Registered 24 years ago, and is one of the largest price comparison sites in the nordics.

**Comment by MadSpindel** [comment]
tv.nu as well. Same owner as prisjakt.nu

**Comment by MadSpindel** [comment]
Maybe it's related to the .NU top domain. jarnvagar.nu is also falsely blocked.

**Comment by miansopi** [comment]
@xRuffKez Status on this? Had to turn NRD off when i noticed that it was also blocking the Swish Payment service. Transactions between two people still worked, even though `api.swish.nu` was blocked.

**Comment by MadSpindel** [comment]
I had to disable as well. Way too many important sites are blocked.

**Comment by MadSpindel** [comment]
This issue is closed but do we know why it happened in the first place? I see that the domains have been added to exclusion list but it's weird why they were marked as NRD?
