### ISSUE TITLE
[Question] Difference between "Phising"-Version and normal

### ISSUE THREAD

**Issue by RichardBeisser** [xRuffKez/NRD#12]
Hello,

i noticed that you split up your lists in a Phishing-Version and a normal Version.
What's the difference?
Does normal Version include domains from phishing version?
How do you select if a domain is for the one or the other version?

Regards

**Comment by LordRishav** [comment]
Would like to know too.

**Comment by xRuffKez** [comment]
https://github.com/hagezi/dns-blocklists/issues/4339#issuecomment-2481121618
