### ISSUE TITLE
[Suggestion] New lists, 60 days NRD

### ISSUE THREAD

**Issue by RichardBeisser** [xRuffKez/NRD#13]
Hello,

I get many Spam-Mails with links using Domains just a little bit older than 30 days.

Examples:
apothekeeuropa.de
shanonlife.shop
terrespout.com
longlifeo.shop
caustrate.com
lokalerversand.nl

It would be great if you offer also a list 60 days NRD.
I know that with 60 days, false positives will increase, so this list should be only used if the user want this.

//EDIT:
Another idea:
Spammers often use Registrars where they can get domains very cheap, like Dynadot.com or Namecheap.com
I suppose when you collect NRD, you also collect the registrar, right? What you do think of a 100day-list of NRDs from critical registrars which are often for crap?

**Comment by NoGitHubForYou** [comment]
I'd love to see a 90 day list but I'd be very happy even with a 60 day list. Too many fake shopping sites surpass 30 days

**Comment by xRuffKez** [comment]
For domains which survive longer then 30 days, i suggest you guys to report the to https://github.com/hagezi/dns-blocklists/issues
This repository is focusing on 14day and 30day NRDs only. Thanks for your suggestion though, but after 30 days some legit domains should reached so "credibility" and should not be blocked. NRD Lists are more like a time buffer for investigating those domains.
