### ISSUE TITLE
monicarelino13512-carelino.click (phising)

### ISSUE THREAD

**Issue by wowfilip999** [xRuffKez/NRD#14]
fake facebook support it tell you to verify you account or you will be blocked 
![image](https://github.com/user-attachments/assets/af2a6d06-601a-4e8e-b6d7-2ecb314447ef)
full url:https://monicarelino13512-carelino.click/253475247
Domain:
monicarelino13512-carelino.click
Registrar:
Sav.com, LLC
Registered On:
2024-11-06
Expires On:
2025-11-06
Updated On:
2024-11-06
Status:
clientTransferProhibited
addPeriod
Name Servers:
laura.ns.cloudflare.com
augustus.ns.cloudflare.com

**Comment by hagezi** [comment]
@iam-py-test

**Comment by xRuffKez** [comment]
Please don't report domains here, which are not in my NRD lists.

Use https://github.com/hagezi/dns-blocklists/issues to report Ads, Trackers etc.
Use https://github.com/iam-py-test/my_filters_001/issues to report Malicious Domains
Use https://github.com/jarelllama/Scam-Blocklist/issues to report Scam

**Comment by iam-py-test** [comment]
Sorry for the delay in responding.
I have blocklisted the reported website.
Thank you
