### ISSUE TITLE
puny code domains

### ISSUE THREAD

**Issue by NoGitHubForYou** [xRuffKez/NRD#15]
At the time of this issue there is, 6K plus in nrd-30day_adblock_part2.txt and 400 nrd-30day_adblock_part1.txt domains that are not able to be blocked in pihole because they're not converted to punycode.

for instance
'könig-trailer.tech' should be converted to 'xn--knig-trailer-4ib.tech'

You could probaly achieve this with 
https://pypi.org/project/pyunycode/

This way we can take advantage of blocking those extra 6400 plus NRDs rather then having pihole ignore them.

Thanks

**Comment by xRuffKez** [comment]
Thanks for your request, i have updated the script to ensure domains who need extra handling are puny coded!
