### ISSUE TITLE
Split 14 & 30 day lists further for use in AdGuard

### ISSUE THREAD

**Issue by GlitchHopAnonymous** [xRuffKez/NRD#16]
Would it be possible to split these lists into smaller sizes than just part 1 & 2? It would be nice to be able to use them in AdGuard.

**Comment by xRuffKez** [comment]
You mean, use them in Adguard App? It is possible but renders your app and maybe phone unusable. There are more then 8mil domains...

I wont further split them, please use Adguard Home or similar as upstream, where you use the lists. Those applications are designed to handle such lists.
