### ISSUE TITLE
Blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [xRuffKez/NRD#2]
[i] Target: https://raw.githubusercontent.com/xRuffKez/NRD/main/nrd-30day_adblock_part1.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 3450920 ABP-style domains (ignored 8 non-domain entries)
      Sample of non-domain entries:
        - "11:02:09^"
        - "11:20:37^"
        - "13:07:28^"
        - "10:00:56^"
        - "09:51:53^"

 [i] Target: https://raw.githubusercontent.com/xRuffKez/NRD/main/nrd-30day_adblock_part2.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 3450925 ABP-style domains (ignored 3 non-domain entries)
      Sample of non-domain entries:
        - "10:43:18^"
        - "10:00:47^"
        - "09:25:35^"

**Comment by hagezi** [comment]
@xRuffKez use `grep -P '(?=^.{4,244}$)(^(?:[a-zA-Z0-9](?:(?:[a-zA-Z0-9\-]){0,61}[a-zA-Z0-9])?\.)+([a-zA-Z]{2,}|xn--[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$)'` in your script to extract only valid domains.

**Comment by hagezi** [comment]
Invalid:

Part1:
```
accountrific.com+2024-05-10 11:02:09
aqzf1.click+2024-05-11 11:20:37
bcn
chemiejinak.cz+2024-05-09 13:07:28
crefdonationx.org+2024-05-08 10:00:56
domainName
ecommerce-57253.bond+2024-05-07 09:51:53
gsseexc638.com+2024-05-08 10:11:11
healthcare-software-60170.bond+2024-05-11 10:17:50
huiyidianzi.com+2024-05-07 09:57:40
```

Part 2:
```
roofing-jobs-54821.bond+2024-05-07 10:43:18
sodcov.com+2024-05-08 10:00:47
themacheesefactory.com+2024-05-05 09:25:35
zxzm15.t60
```

**Comment by xRuffKez** [comment]
Thanks for the report, i'm working on it.

**Comment by xRuffKez** [comment]
@hagezi thanks for the regex! Can you confirm that there are only valid domains now?

**Comment by xRuffKez** [comment]
> @xRuffKez use `grep -P '(?=^.{4,244}$)(^(?:[a-zA-Z0-9](?:(?:[a-zA-Z0-9\-]){0,61}[a-zA-Z0-9])?\.)+([a-zA-Z]{2,}|xn--[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$)'` in your script to extract only valid domains.

I think

```
^(?=.{4,244}$)(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*(?:[a-zA-Z]{2,}|xn\-\-[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$
```
is more suitable?

**Comment by hagezi** [comment]
> Can you confirm that there are only valid domains now?

No ...

`curl -sL https://raw.githubusercontent.com/xRuffKez/NRD/main/nrd-30day_part1.txt | grep -Pv '(?=^.{4,244}$)(^(?:[a-zA-Z0-9](?:(?:[a-zA-Z0-9\-]){0,61}[a-zA-Z0-9])?\.)+([a-zA-Z]{2,}|xn--[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$)'
`
```
accountrific.com+2024-05-10 11:02:09
aqzf1.click+2024-05-11 11:20:37
bcn
chemiejinak.cz+2024-05-09 13:07:28
crefdonationx.org+2024-05-08 10:00:56
domainName
ecommerce-57253.bond+2024-05-07 09:51:53
gsseexc638.com+2024-05-08 10:11:11
healthcare-software-60170.bond+2024-05-11 10:17:50
huiyidianzi.com+2024-05-07 09:57:40


```

**Comment by xRuffKez** [comment]
Should be fixed now 🫡
