### ISSUE TITLE
blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [xRuffKez/NRD#6]
[i] Target: https://raw.githubusercontent.com/xRuffKez/NRD/main/nrd-30day_adblock_part1.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 3499879 ABP-style domains (ignored 588 non-domain entries)
      Sample of non-domain entries:
        - "||-všetkyy0pk7.today^"
        - "||01dosmétodos.online^"
        - "||0å0.net^"
        - "||1lodówka-pl.today^"
        - "||1табачный.online^"

**Comment by xRuffKez** [comment]
These are valid domains with non standard encoding!

**Comment by xRuffKez** [comment]
https://github.com/xRuffKez/NRD/issues/8

**Comment by xRuffKez** [comment]
List is not Puny Coded
