### ISSUE TITLE
Blocklist Cleanup #2

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [xRuffKez/NRD#7]
https://raw.githubusercontent.com/xRuffKez/NRD/main/nrd-30day_adblock_part2.txt

 [✓] Parsed 0 exact domains and 3495384 ABP-style domains (ignored 5088 non-domain entries)
      Sample of non-domain entries:
        - "||koupit-nejnovější-iphonee0p.today^"
        - "||kraftmüller.net^"
        - "||kraftmüllerpro.net^"
        - "||kreditkartenfüralle.today^"
        - "||kreditkartenfürsie.today^"

**Comment by xRuffKez** [comment]
Valid Domains with non standard encoding!

**Comment by xRuffKez** [comment]
https://github.com/xRuffKez/NRD/issues/8
