### ISSUE TITLE
question: how exactly phishing nrds gets detected?

### ISSUE THREAD

**Issue by pokegamer5547** [xRuffKez/NRD#9]
The list is too large so i'm considering using atleast phishing nrd list but i would like to know how exactly it considers something as phishing site.

**Comment by xRuffKez** [comment]
Mainly typosquatting, homographic and domains which look like a company but is not associated. Then there are enthropies of domains, which are likely automatically registered and have bad reputation.

**Comment by pokegamer5547** [comment]
Thanyou for such quick reply! :)

> Mainly typosquatting, homographic and domains which look like a company but is not associated.

So it's like, you check the owners of these domains and see whether it's matching the original name or not?
And by homographic, you mean like non ascii character domains right? 

>  Then there are enthropies of domains, which are likely automatically registered and have bad reputation.

Where does this list get that entrophies list from?

**Comment by xRuffKez** [comment]
> And by homographic, you mean like non ascii character domains right?

Exactly 👍
